### ISSUE TITLE
error because of space in select list 

### ISSUE THREAD

**Issue by harry-dietz** [d-velop/grafana-odata-datasource#22]
Hi,
all looks good when using the odata plugin until I try to add fields to the result. Then our server fails because the query is doing things like "select=field1, field2, field3" instead of "select=field1,field2,field3"
There is a space after the comma and this is not part of the odata spec. 

Can you please adjust the code so this is going away? I think the fix is to be done in pkg/plugin/client.go method mapSelect:
func mapSelect(properties []property, timeProperty string) string {
	var result []string
	if len(properties) > 0 {
		for _, selectProp := range properties {
			result = append(result, selectProp.Name)
		}
	}
	if len(timeProperty) > 0 {
		result = append(result, timeProperty)
	}
	return strings.Join(result[:], ", ")   ---> should be return strings.Join(result[:], ",")
}

Kind regards
Harry

**Comment by carroe** [comment]
Hi Harry,

has already been fixed in the feature-new-test-server branch. I've cherry-picked this from there in master. See https://github.com/d-velop/grafana-odata-datasource/commit/93f8422609f2035e34f3f6fbabac9ecbf4696bb4

Will be part of the next version that we will release in the next 2-3 weeks.

Best regards
Carsten

**Comment by carroe** [comment]
Fix has been released in v1.1.0
